"""
Alert rules engine for Zedd Weather.
Evaluates telemetry against configurable thresholds and generates alerts.
"""
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Optional


class AlertSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class Alert:
    """A single alert generated by the rules engine."""
    id: str
    severity: AlertSeverity
    title: str
    message: str
    metric: str
    value: float
    threshold: float
    timestamp: datetime
    crop: Optional[str] = None


@dataclass
class AlertRule:
    """Configurable rule that evaluates one telemetry metric against a threshold."""
    name: str
    metric: str
    condition: str          # ">", "<", ">=", "<=", "=="
    threshold: float
    severity: AlertSeverity
    message_template: str   # supports {value} and {threshold} placeholders
    enabled: bool = True


class AlertRulesEngine:
    """
    Evaluates a set of AlertRules against a telemetry snapshot and returns
    any triggered Alert objects.
    """

    DEFAULT_RULES: list[AlertRule] = [
        # --- Temperature ---
        AlertRule(
            name="Extreme Heat",
            metric="temperature",
            condition=">",
            threshold=40.0,
            severity=AlertSeverity.CRITICAL,
            message_template=(
                "Temperature {value}°C exceeds critical threshold of {threshold}°C. "
                "Crop damage likely."
            ),
        ),
        AlertRule(
            name="High Temperature",
            metric="temperature",
            condition=">",
            threshold=35.0,
            severity=AlertSeverity.WARNING,
            message_template=(
                "Temperature {value}°C is above heat-stress threshold ({threshold}°C)."
            ),
        ),
        AlertRule(
            name="Frost Risk",
            metric="temperature",
            condition="<",
            threshold=2.0,
            severity=AlertSeverity.CRITICAL,
            message_template=(
                "Temperature {value}°C is near or below freezing ({threshold}°C). "
                "Frost protection required."
            ),
        ),
        AlertRule(
            name="Low Temperature",
            metric="temperature",
            condition="<",
            threshold=8.0,
            severity=AlertSeverity.WARNING,
            message_template=(
                "Temperature {value}°C is below cold-stress threshold ({threshold}°C)."
            ),
        ),
        # --- Humidity ---
        AlertRule(
            name="Very High Humidity",
            metric="humidity",
            condition=">=",
            threshold=90.0,
            severity=AlertSeverity.CRITICAL,
            message_template=(
                "Humidity {value}% has reached critical level ({threshold}%). "
                "High disease risk."
            ),
        ),
        AlertRule(
            name="High Humidity",
            metric="humidity",
            condition=">",
            threshold=80.0,
            severity=AlertSeverity.WARNING,
            message_template="Humidity {value}% exceeds {threshold}%. Monitor for fungal disease.",
        ),
        AlertRule(
            name="Low Humidity",
            metric="humidity",
            condition="<",
            threshold=30.0,
            severity=AlertSeverity.WARNING,
            message_template=(
                "Humidity {value}% is below {threshold}%. "
                "Increased pest risk and evapotranspiration."
            ),
        ),
        # --- Pressure ---
        AlertRule(
            name="Storm Pressure",
            metric="pressure",
            condition="<",
            threshold=980.0,
            severity=AlertSeverity.CRITICAL,
            message_template=(
                "Atmospheric pressure {value} hPa is critically low ({threshold} hPa). "
                "Severe storm likely."
            ),
        ),
        AlertRule(
            name="Low Pressure",
            metric="pressure",
            condition="<",
            threshold=995.0,
            severity=AlertSeverity.WARNING,
            message_template=(
                "Pressure {value} hPa is below {threshold} hPa. Weather deterioration possible."
            ),
        ),
    ]

    def __init__(self, rules: Optional[list[AlertRule]] = None) -> None:
        self._rules: list[AlertRule] = list(rules) if rules is not None else list(self.DEFAULT_RULES)

    # ---------------------------------------------------------------------------
    # Public API
    # ---------------------------------------------------------------------------

    def evaluate(self, telemetry: dict, crop: Optional[str] = None) -> list[Alert]:
        """
        Evaluate all enabled rules against the telemetry snapshot.

        Parameters
        ----------
        telemetry:
            Dict with numeric metric values (temperature, humidity, pressure, …).
        crop:
            Optional crop name; attached to generated Alert objects for context.

        Returns
        -------
        List of triggered Alert objects, ordered by severity (critical first).
        """
        alerts: list[Alert] = []
        now = datetime.now(tz=timezone.utc)

        for rule in self._rules:
            if not rule.enabled:
                continue
            raw = telemetry.get(rule.metric)
            if raw is None:
                continue
            value = float(raw)
            if self._matches(value, rule.condition, rule.threshold):
                alerts.append(Alert(
                    id=str(uuid.uuid4()),
                    severity=rule.severity,
                    title=rule.name,
                    message=rule.message_template.format(
                        value=round(value, 2),
                        threshold=rule.threshold,
                    ),
                    metric=rule.metric,
                    value=value,
                    threshold=rule.threshold,
                    timestamp=now,
                    crop=crop,
                ))

        # Sort: CRITICAL first, then WARNING, then INFO
        severity_order = {
            AlertSeverity.CRITICAL: 0,
            AlertSeverity.WARNING: 1,
            AlertSeverity.INFO: 2,
        }
        alerts.sort(key=lambda a: severity_order.get(a.severity, 99))
        return alerts

    def add_rule(self, rule: AlertRule) -> None:
        """Append a custom rule to the engine."""
        self._rules.append(rule)

    # ---------------------------------------------------------------------------
    # Private helpers
    # ---------------------------------------------------------------------------

    @staticmethod
    def _matches(value: float, condition: str, threshold: float) -> bool:
        """Evaluate value condition threshold."""
        ops = {
            ">": value > threshold,
            "<": value < threshold,
            ">=": value >= threshold,
            "<=": value <= threshold,
            "==": value == threshold,
        }
        return ops.get(condition, False)
