"""
Zedd Weather — Email Reporter
Sends HTML-formatted weather risk reports via SMTP.
"""
from __future__ import annotations

import logging
import os
import smtplib
from dataclasses import dataclass, field
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class EmailConfig:
    smtp_host: str = "localhost"
    smtp_port: int = 587
    smtp_user: str | None = None
    smtp_password: str | None = None
    use_tls: bool = True
    from_addr: str = "zedd-weather@localhost"
    to_addrs: list[str] = field(default_factory=list)


def _load_config_from_env() -> EmailConfig:
    return EmailConfig(
        smtp_host=os.getenv("SMTP_HOST", "localhost"),
        smtp_port=int(os.getenv("SMTP_PORT", "587")),
        smtp_user=os.getenv("SMTP_USER") or None,
        smtp_password=os.getenv("SMTP_PASSWORD") or None,
        use_tls=os.getenv("SMTP_USE_TLS", "true").lower() == "true",
        from_addr=os.getenv("SMTP_FROM", "zedd-weather@localhost"),
        to_addrs=[a.strip() for a in os.getenv("SMTP_TO", "").split(",") if a.strip()],
    )


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: #0a0a0a; color: #e2e8f0; margin: 0; padding: 20px; }}
  .container {{ max-width: 700px; margin: 0 auto; }}
  .header {{ border-bottom: 1px solid #1e293b; padding-bottom: 16px; margin-bottom: 24px; }}
  .header h1 {{ margin: 0; font-size: 22px; }}
  .header .sub {{ color: #94a3b8; font-size: 12px; }}
  .card {{ background: #111111; border: 1px solid #1e293b; border-radius: 10px;
           padding: 16px; margin-bottom: 16px; }}
  .card h2 {{ font-size: 14px; color: #cbd5e1; margin: 0 0 12px 0; }}
  .badge {{ display: inline-block; padding: 4px 14px; border-radius: 6px;
            font-size: 13px; font-weight: 700; text-transform: uppercase;
            letter-spacing: 0.08em; }}
  .badge-low {{ background: rgba(34,197,94,0.12); color: #22c55e; border: 1px solid rgba(34,197,94,0.3); }}
  .badge-medium {{ background: rgba(245,158,11,0.12); color: #f59e0b; border: 1px solid rgba(245,158,11,0.3); }}
  .badge-high {{ background: rgba(239,68,68,0.12); color: #ef4444; border: 1px solid rgba(239,68,68,0.3); }}
  .badge-critical {{ background: rgba(156,163,175,0.12); color: #9ca3af; border: 1px solid rgba(156,163,175,0.3); }}
  .rec {{ font-size: 13px; color: #94a3b8; margin: 4px 0; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ text-align: left; color: #94a3b8; padding: 6px 8px; border-bottom: 1px solid #1e293b; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #1e293b; color: #e2e8f0; }}
  .footer {{ text-align: center; color: #475569; font-size: 11px; margin-top: 24px; }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>☁ Zedd Weather Report</h1>
    <div class="sub">{timestamp} &middot; {region}</div>
  </div>
  {sections}
  <div class="footer">
    Generated by Zedd Weather Enterprise &middot; All analysis is heuristic-based.
  </div>
</div>
</body>
</html>
"""


def _risk_badge_html(level: str | None) -> str:
    text = str(level or "unknown")
    cls = f"badge-{text.lower()}" if text.lower() in ("low", "medium", "high", "critical") else "badge-medium"
    return f'<span class="badge {cls}">{text}</span>'


def _build_report_html(
    results: dict[str, Any],
    region: str = "Midlands",
) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections_html = ""

    for sector, analysis in results.items():
        risk = analysis.get("risk_level", "N/A")
        recs = analysis.get("recommendations", [])
        region_name = analysis.get("region", region)

        detail_rows = ""
        for k, v in analysis.items():
            if k in ("risk_level", "recommendations", "region", "season", "vessel", "facility_type",
                     "property_type", "aircraft", "asset", "transport_mode",
                     "vessel_name", "facility_name", "property_name", "aircraft_name",
                     "asset_name", "mode_name"):
                continue
            if isinstance(v, dict):
                for sk, sv in v.items():
                    if isinstance(sv, list):
                        detail_rows += f"<tr><td>{k}.{sk}</td><td>{', '.join(str(x) for x in sv[:3])}</td></tr>"
                    else:
                        detail_rows += f"<tr><td>{k}.{sk}</td><td>{sv}</td></tr>"
            elif isinstance(v, list):
                items = [str(x.get("risk", x.get("hazard", x.get("phase", str(x))))) for x in v[:5]]
                detail_rows += f"<tr><td>{k}</td><td>{', '.join(items)}</td></tr>"
            else:
                detail_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"

        rec_html = "".join(f'<li class="rec">{r}</li>' for r in recs[:5]) if recs else ""

        section = f"""\
<div class="card">
  <h2>{sector.title()} — {_risk_badge_html(risk)}</h2>
  <table>
    <tr><th>Region</th><td>{region_name}</td></tr>
    {detail_rows}
  </table>
  {("<ul style='margin:8px 0 0 0;padding-left:20px'>" + rec_html + "</ul>") if rec_html else ""}
</div>
"""
        sections_html += section

    return _HTML_TEMPLATE.format(timestamp=timestamp, region=region, sections=sections_html)


def send_report(
    results: dict[str, Any],
    region: str = "Midlands",
    config: EmailConfig | None = None,
) -> bool:
    cfg = config or _load_config_from_env()
    if not cfg.to_addrs:
        logger.warning("No SMTP_TO recipients configured. Skipping email.")
        return False

    html = _build_report_html(results, region)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Zedd Weather Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    msg["From"] = cfg.from_addr
    msg["To"] = ", ".join(cfg.to_addrs)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port) as server:
            if cfg.use_tls:
                server.starttls()
            if cfg.smtp_user and cfg.smtp_password:
                server.login(cfg.smtp_user, cfg.smtp_password)
            server.sendmail(cfg.from_addr, cfg.to_addrs, msg.as_string())
        logger.info("Report sent to %s", cfg.to_addrs)
        return True
    except Exception as exc:
        logger.exception("Failed to send report: %s", exc)
        return False


def send_sector_report(
    sector: str,
    analysis: dict[str, Any],
    config: EmailConfig | None = None,
) -> bool:
    return send_report({sector: analysis}, region=analysis.get("region", "Midlands"), config=config)
