"""
Zedd Weather — Email Reporter
Sends HTML-formatted weather risk reports via SMTP.
"""
from __future__ import annotations

import logging
import os
import smtplib
from dataclasses import dataclass, field
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from datetime import datetime, timezone
from typing import Any

logger = logging.getLogger(__name__)


@dataclass
class EmailConfig:
    smtp_host: str = "localhost"
    smtp_port: int = 587
    smtp_user: str | None = None
    smtp_password: str | None = None
    use_tls: bool = True
    from_addr: str = "zedd-weather@localhost"
    to_addrs: list[str] = field(default_factory=list)


def _load_config_from_env() -> EmailConfig:
    return EmailConfig(
        smtp_host=os.getenv("SMTP_HOST", "localhost"),
        smtp_port=int(os.getenv("SMTP_PORT", "587")),
        smtp_user=os.getenv("SMTP_USER") or None,
        smtp_password=os.getenv("SMTP_PASSWORD") or None,
        use_tls=os.getenv("SMTP_USE_TLS", "true").lower() == "true",
        from_addr=os.getenv("SMTP_FROM", "zedd-weather@localhost"),
        to_addrs=[a.strip() for a in os.getenv("SMTP_TO", "").split(",") if a.strip()],
    )


_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         background: #0a0a0a; color: #e2e8f0; margin: 0; padding: 20px;
         -webkit-font-smoothing: antialiased; }}
  .container {{ max-width: 700px; margin: 0 auto; }}
  .header {{ border-bottom: 2px solid #1e293b; padding-bottom: 20px; margin-bottom: 24px; }}
  .header h1 {{ margin: 0; font-size: 24px; font-weight: 800; letter-spacing: -0.02em; color: #f1f5f9; }}
  .header .sub {{ color: #64748b; font-size: 13px; margin-top: 4px; }}
  .header .sub span {{ color: #10b981; }}
  .card {{ background: linear-gradient(135deg, #111111 0%, #141414 100%);
           border: 1px solid #1e293b; border-radius: 12px;
           padding: 20px; margin-bottom: 16px; }}
  .card h2 {{ font-size: 15px; color: #e2e8f0; margin: 0 0 14px 0;
              font-weight: 700; display: flex; align-items: center; gap: 10px; }}
  .risk-bar {{ height: 4px; border-radius: 2px; margin-bottom: 14px;
               background: linear-gradient(90deg, var(--rbar) 0%, var(--rbar) var(--rpct), #1e293b var(--rpct), #1e293b 100%); }}
  .badge {{ display: inline-block; padding: 3px 12px; border-radius: 5px;
            font-size: 11px; font-weight: 700; text-transform: uppercase;
            letter-spacing: 0.08em; }}
  .badge-low {{ background: rgba(34,197,94,0.15); color: #4ade80; border: 1px solid rgba(34,197,94,0.3); }}
  .badge-medium {{ background: rgba(245,158,11,0.15); color: #fbbf24; border: 1px solid rgba(245,158,11,0.3); }}
  .badge-high {{ background: rgba(239,68,68,0.15); color: #f87171; border: 1px solid rgba(239,68,68,0.3); }}
  .badge-critical {{ background: rgba(156,163,175,0.15); color: #9ca3af; border: 1px solid rgba(156,163,175,0.3); }}
  .rec {{ font-size: 13px; color: #94a3b8; margin: 5px 0; padding-left: 4px;
          border-left: 2px solid #1e293b; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px; }}
  th {{ text-align: left; color: #64748b; padding: 5px 8px; border-bottom: 1px solid #1e293b;
        font-weight: 600; width: 40%; }}
  td {{ padding: 5px 8px; border-bottom: 1px solid #1e293b; color: #e2e8f0; }}
  tr:last-child th, tr:last-child td {{ border-bottom: none; }}
  .footer {{ text-align: center; color: #334155; font-size: 11px; margin-top: 28px;
             border-top: 1px solid #1e293b; padding-top: 16px; }}
  @media (max-width: 600px) {{
    body {{ padding: 12px; }}
    .card {{ padding: 14px; }}
    table, th, td {{ font-size: 12px; }}
  }}
</style>
</head>
<body>
<div class="container">
  <div class="header">
    <h1>☁ Zedd Weather Report</h1>
    <div class="sub"><span>{timestamp}</span> &middot; {region}</div>
  </div>
  {sections}
  <div class="footer">
    Generated by Zedd Weather Enterprise &middot; All analysis is heuristic-based.
  </div>
</div>
</body>
</html>
"""


RISK_LEVEL_PCT: dict[str, int] = {
    "low": 15, "medium": 40, "high": 70, "critical": 95,
}
RISK_LEVEL_COLORS: dict[str, str] = {
    "low": "#22c55e", "medium": "#f59e0b", "high": "#ef4444", "critical": "#9ca3af",
}


def _risk_badge_html(level: str | None) -> str:
    text = str(level or "unknown")
    key = text.lower()
    cls = f"badge-{key}" if key in ("low", "medium", "high", "critical") else "badge-medium"
    return f'<span class="badge {cls}">{text}</span>'


def _risk_bar_html(level: str | None) -> str:
    key = str(level or "medium").lower()
    pct = RISK_LEVEL_PCT.get(key, 40)
    color = RISK_LEVEL_COLORS.get(key, "#f59e0b")
    return f'<div class="risk-bar" style="--rbar:{color};--rpct:{pct}%"></div>'


def _build_report_html(
    results: dict[str, Any],
    region: str = "Midlands",
) -> str:
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections_html = ""

    for sector, analysis in results.items():
        risk = analysis.get("risk_level", "N/A")
        recs = analysis.get("recommendations", [])
        region_name = analysis.get("region", region)

        detail_rows = ""
        for k, v in analysis.items():
            if k in ("risk_level", "recommendations", "region", "season", "vessel", "facility_type",
                     "property_type", "aircraft", "asset", "transport_mode",
                     "vessel_name", "facility_name", "property_name", "aircraft_name",
                     "asset_name", "mode_name"):
                continue
            if isinstance(v, dict):
                for sk, sv in v.items():
                    if isinstance(sv, list):
                        detail_rows += f"<tr><td>{k}.{sk}</td><td>{', '.join(str(x) for x in sv[:3])}</td></tr>"
                    else:
                        detail_rows += f"<tr><td>{k}.{sk}</td><td>{sv}</td></tr>"
            elif isinstance(v, list):
                items = [str(x.get("risk", x.get("hazard", x.get("phase", str(x))))) for x in v[:5]]
                detail_rows += f"<tr><td>{k}</td><td>{', '.join(items)}</td></tr>"
            else:
                detail_rows += f"<tr><td>{k}</td><td>{v}</td></tr>"

        rec_html = "".join(f'<li class="rec">{r}</li>' for r in recs[:5]) if recs else ""

        section = f"""\
<div class="card">
  <h2>{sector.title()}  {_risk_badge_html(risk)}</h2>
  {_risk_bar_html(risk)}
  <table>
    <tr><th>Region</th><td>{region_name}</td></tr>
    {detail_rows}
  </table>
  {("<ul style='margin:10px 0 0 0;padding-left:4px'>" + rec_html + "</ul>") if rec_html else ""}
</div>
"""
        sections_html += section

    return _HTML_TEMPLATE.format(timestamp=timestamp, region=region, sections=sections_html)


def send_report(
    results: dict[str, Any],
    region: str = "Midlands",
    config: EmailConfig | None = None,
) -> bool:
    cfg = config or _load_config_from_env()
    if not cfg.to_addrs:
        logger.warning("No SMTP_TO recipients configured. Skipping email.")
        return False

    html = _build_report_html(results, region)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Zedd Weather Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}"
    msg["From"] = cfg.from_addr
    msg["To"] = ", ".join(cfg.to_addrs)
    msg.attach(MIMEText(html, "html"))

    try:
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port) as server:
            if cfg.use_tls:
                server.starttls()
            if cfg.smtp_user and cfg.smtp_password:
                server.login(cfg.smtp_user, cfg.smtp_password)
            server.sendmail(cfg.from_addr, cfg.to_addrs, msg.as_string())
        logger.info("Report sent to %s", cfg.to_addrs)
        return True
    except Exception as exc:
        logger.exception("Failed to send report: %s", exc)
        return False


def send_sector_report(
    sector: str,
    analysis: dict[str, Any],
    config: EmailConfig | None = None,
) -> bool:
    return send_report({sector: analysis}, region=analysis.get("region", "Midlands"), config=config)
